'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace LoginService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://dylanh-dev.com/", ConfigurationName:="LoginService.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://dylanh-dev.com/SQLTest", ReplyAction:="*")>  _
        Function SQLTest() As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://dylanh-dev.com/SQLTest", ReplyAction:="*")>  _
        Function SQLTestAsync() As System.Threading.Tasks.Task(Of Boolean)
        
        'CODEGEN: Generating message contract since element name UsernameEntered from namespace http://dylanh-dev.com/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://dylanh-dev.com/VerifyLogin", ReplyAction:="*")>  _
        Function VerifyLogin(ByVal request As LoginService.VerifyLoginRequest) As LoginService.VerifyLoginResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://dylanh-dev.com/VerifyLogin", ReplyAction:="*")>  _
        Function VerifyLoginAsync(ByVal request As LoginService.VerifyLoginRequest) As System.Threading.Tasks.Task(Of LoginService.VerifyLoginResponse)
        
        'CODEGEN: Generating message contract since element name UsernameEntered from namespace http://dylanh-dev.com/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://dylanh-dev.com/RegisterNewUser", ReplyAction:="*")>  _
        Function RegisterNewUser(ByVal request As LoginService.RegisterNewUserRequest) As LoginService.RegisterNewUserResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://dylanh-dev.com/RegisterNewUser", ReplyAction:="*")>  _
        Function RegisterNewUserAsync(ByVal request As LoginService.RegisterNewUserRequest) As System.Threading.Tasks.Task(Of LoginService.RegisterNewUserResponse)
        
        'CODEGEN: Generating message contract since element name UsernameEntered from namespace http://dylanh-dev.com/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://dylanh-dev.com/CheckExistingUser", ReplyAction:="*")>  _
        Function CheckExistingUser(ByVal request As LoginService.CheckExistingUserRequest) As LoginService.CheckExistingUserResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://dylanh-dev.com/CheckExistingUser", ReplyAction:="*")>  _
        Function CheckExistingUserAsync(ByVal request As LoginService.CheckExistingUserRequest) As System.Threading.Tasks.Task(Of LoginService.CheckExistingUserResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class VerifyLoginRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="VerifyLogin", [Namespace]:="http://dylanh-dev.com/", Order:=0)>  _
        Public Body As LoginService.VerifyLoginRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As LoginService.VerifyLoginRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://dylanh-dev.com/")>  _
    Partial Public Class VerifyLoginRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UsernameEntered As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public PasswordEntered As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UsernameEntered As String, ByVal PasswordEntered As String)
            MyBase.New
            Me.UsernameEntered = UsernameEntered
            Me.PasswordEntered = PasswordEntered
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class VerifyLoginResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="VerifyLoginResponse", [Namespace]:="http://dylanh-dev.com/", Order:=0)>  _
        Public Body As LoginService.VerifyLoginResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As LoginService.VerifyLoginResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://dylanh-dev.com/")>  _
    Partial Public Class VerifyLoginResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public VerifyLoginResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal VerifyLoginResult As Boolean)
            MyBase.New
            Me.VerifyLoginResult = VerifyLoginResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RegisterNewUserRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RegisterNewUser", [Namespace]:="http://dylanh-dev.com/", Order:=0)>  _
        Public Body As LoginService.RegisterNewUserRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As LoginService.RegisterNewUserRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://dylanh-dev.com/")>  _
    Partial Public Class RegisterNewUserRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UsernameEntered As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public PasswordEntered As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public FirstNameEntered As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public LastNameEntered As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public MobilePhoneEntered As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public EmailEntered As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public BirthdayEntered As Date
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UsernameEntered As String, ByVal PasswordEntered As String, ByVal FirstNameEntered As String, ByVal LastNameEntered As String, ByVal MobilePhoneEntered As String, ByVal EmailEntered As String, ByVal BirthdayEntered As Date)
            MyBase.New
            Me.UsernameEntered = UsernameEntered
            Me.PasswordEntered = PasswordEntered
            Me.FirstNameEntered = FirstNameEntered
            Me.LastNameEntered = LastNameEntered
            Me.MobilePhoneEntered = MobilePhoneEntered
            Me.EmailEntered = EmailEntered
            Me.BirthdayEntered = BirthdayEntered
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class RegisterNewUserResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="RegisterNewUserResponse", [Namespace]:="http://dylanh-dev.com/", Order:=0)>  _
        Public Body As LoginService.RegisterNewUserResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As LoginService.RegisterNewUserResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://dylanh-dev.com/")>  _
    Partial Public Class RegisterNewUserResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public RegisterNewUserResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal RegisterNewUserResult As Boolean)
            MyBase.New
            Me.RegisterNewUserResult = RegisterNewUserResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CheckExistingUserRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CheckExistingUser", [Namespace]:="http://dylanh-dev.com/", Order:=0)>  _
        Public Body As LoginService.CheckExistingUserRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As LoginService.CheckExistingUserRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://dylanh-dev.com/")>  _
    Partial Public Class CheckExistingUserRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public UsernameEntered As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public EmailEntered As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public MobilePhoneEntered As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal UsernameEntered As String, ByVal EmailEntered As String, ByVal MobilePhoneEntered As String)
            MyBase.New
            Me.UsernameEntered = UsernameEntered
            Me.EmailEntered = EmailEntered
            Me.MobilePhoneEntered = MobilePhoneEntered
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class CheckExistingUserResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="CheckExistingUserResponse", [Namespace]:="http://dylanh-dev.com/", Order:=0)>  _
        Public Body As LoginService.CheckExistingUserResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As LoginService.CheckExistingUserResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://dylanh-dev.com/")>  _
    Partial Public Class CheckExistingUserResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public CheckExistingUserResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal CheckExistingUserResult As Boolean)
            MyBase.New
            Me.CheckExistingUserResult = CheckExistingUserResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits LoginService.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of LoginService.WebService1Soap)
        Implements LoginService.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function SQLTest() As Boolean Implements LoginService.WebService1Soap.SQLTest
            Return MyBase.Channel.SQLTest
        End Function
        
        Public Function SQLTestAsync() As System.Threading.Tasks.Task(Of Boolean) Implements LoginService.WebService1Soap.SQLTestAsync
            Return MyBase.Channel.SQLTestAsync
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function LoginService_WebService1Soap_VerifyLogin(ByVal request As LoginService.VerifyLoginRequest) As LoginService.VerifyLoginResponse Implements LoginService.WebService1Soap.VerifyLogin
            Return MyBase.Channel.VerifyLogin(request)
        End Function
        
        Public Function VerifyLogin(ByVal UsernameEntered As String, ByVal PasswordEntered As String) As Boolean
            Dim inValue As LoginService.VerifyLoginRequest = New LoginService.VerifyLoginRequest()
            inValue.Body = New LoginService.VerifyLoginRequestBody()
            inValue.Body.UsernameEntered = UsernameEntered
            inValue.Body.PasswordEntered = PasswordEntered
            Dim retVal As LoginService.VerifyLoginResponse = CType(Me,LoginService.WebService1Soap).VerifyLogin(inValue)
            Return retVal.Body.VerifyLoginResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function LoginService_WebService1Soap_VerifyLoginAsync(ByVal request As LoginService.VerifyLoginRequest) As System.Threading.Tasks.Task(Of LoginService.VerifyLoginResponse) Implements LoginService.WebService1Soap.VerifyLoginAsync
            Return MyBase.Channel.VerifyLoginAsync(request)
        End Function
        
        Public Function VerifyLoginAsync(ByVal UsernameEntered As String, ByVal PasswordEntered As String) As System.Threading.Tasks.Task(Of LoginService.VerifyLoginResponse)
            Dim inValue As LoginService.VerifyLoginRequest = New LoginService.VerifyLoginRequest()
            inValue.Body = New LoginService.VerifyLoginRequestBody()
            inValue.Body.UsernameEntered = UsernameEntered
            inValue.Body.PasswordEntered = PasswordEntered
            Return CType(Me,LoginService.WebService1Soap).VerifyLoginAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function LoginService_WebService1Soap_RegisterNewUser(ByVal request As LoginService.RegisterNewUserRequest) As LoginService.RegisterNewUserResponse Implements LoginService.WebService1Soap.RegisterNewUser
            Return MyBase.Channel.RegisterNewUser(request)
        End Function
        
        Public Function RegisterNewUser(ByVal UsernameEntered As String, ByVal PasswordEntered As String, ByVal FirstNameEntered As String, ByVal LastNameEntered As String, ByVal MobilePhoneEntered As String, ByVal EmailEntered As String, ByVal BirthdayEntered As Date) As Boolean
            Dim inValue As LoginService.RegisterNewUserRequest = New LoginService.RegisterNewUserRequest()
            inValue.Body = New LoginService.RegisterNewUserRequestBody()
            inValue.Body.UsernameEntered = UsernameEntered
            inValue.Body.PasswordEntered = PasswordEntered
            inValue.Body.FirstNameEntered = FirstNameEntered
            inValue.Body.LastNameEntered = LastNameEntered
            inValue.Body.MobilePhoneEntered = MobilePhoneEntered
            inValue.Body.EmailEntered = EmailEntered
            inValue.Body.BirthdayEntered = BirthdayEntered
            Dim retVal As LoginService.RegisterNewUserResponse = CType(Me,LoginService.WebService1Soap).RegisterNewUser(inValue)
            Return retVal.Body.RegisterNewUserResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function LoginService_WebService1Soap_RegisterNewUserAsync(ByVal request As LoginService.RegisterNewUserRequest) As System.Threading.Tasks.Task(Of LoginService.RegisterNewUserResponse) Implements LoginService.WebService1Soap.RegisterNewUserAsync
            Return MyBase.Channel.RegisterNewUserAsync(request)
        End Function
        
        Public Function RegisterNewUserAsync(ByVal UsernameEntered As String, ByVal PasswordEntered As String, ByVal FirstNameEntered As String, ByVal LastNameEntered As String, ByVal MobilePhoneEntered As String, ByVal EmailEntered As String, ByVal BirthdayEntered As Date) As System.Threading.Tasks.Task(Of LoginService.RegisterNewUserResponse)
            Dim inValue As LoginService.RegisterNewUserRequest = New LoginService.RegisterNewUserRequest()
            inValue.Body = New LoginService.RegisterNewUserRequestBody()
            inValue.Body.UsernameEntered = UsernameEntered
            inValue.Body.PasswordEntered = PasswordEntered
            inValue.Body.FirstNameEntered = FirstNameEntered
            inValue.Body.LastNameEntered = LastNameEntered
            inValue.Body.MobilePhoneEntered = MobilePhoneEntered
            inValue.Body.EmailEntered = EmailEntered
            inValue.Body.BirthdayEntered = BirthdayEntered
            Return CType(Me,LoginService.WebService1Soap).RegisterNewUserAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function LoginService_WebService1Soap_CheckExistingUser(ByVal request As LoginService.CheckExistingUserRequest) As LoginService.CheckExistingUserResponse Implements LoginService.WebService1Soap.CheckExistingUser
            Return MyBase.Channel.CheckExistingUser(request)
        End Function
        
        Public Function CheckExistingUser(ByVal UsernameEntered As String, ByVal EmailEntered As String, ByVal MobilePhoneEntered As String) As Boolean
            Dim inValue As LoginService.CheckExistingUserRequest = New LoginService.CheckExistingUserRequest()
            inValue.Body = New LoginService.CheckExistingUserRequestBody()
            inValue.Body.UsernameEntered = UsernameEntered
            inValue.Body.EmailEntered = EmailEntered
            inValue.Body.MobilePhoneEntered = MobilePhoneEntered
            Dim retVal As LoginService.CheckExistingUserResponse = CType(Me,LoginService.WebService1Soap).CheckExistingUser(inValue)
            Return retVal.Body.CheckExistingUserResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function LoginService_WebService1Soap_CheckExistingUserAsync(ByVal request As LoginService.CheckExistingUserRequest) As System.Threading.Tasks.Task(Of LoginService.CheckExistingUserResponse) Implements LoginService.WebService1Soap.CheckExistingUserAsync
            Return MyBase.Channel.CheckExistingUserAsync(request)
        End Function
        
        Public Function CheckExistingUserAsync(ByVal UsernameEntered As String, ByVal EmailEntered As String, ByVal MobilePhoneEntered As String) As System.Threading.Tasks.Task(Of LoginService.CheckExistingUserResponse)
            Dim inValue As LoginService.CheckExistingUserRequest = New LoginService.CheckExistingUserRequest()
            inValue.Body = New LoginService.CheckExistingUserRequestBody()
            inValue.Body.UsernameEntered = UsernameEntered
            inValue.Body.EmailEntered = EmailEntered
            inValue.Body.MobilePhoneEntered = MobilePhoneEntered
            Return CType(Me,LoginService.WebService1Soap).CheckExistingUserAsync(inValue)
        End Function
    End Class
End Namespace
